### ISSUE TITLE
Can I hide FoldLine and show FoldLineCurrent only?

### ISSUE THREAD

**Issue by chaneyzorn** [gh-liu/fold_line.nvim#3]
Currently, I use both indent-blankline.nvim and mini.indentscope. They all have some differences.

Your plugin also brings new markup that is very helpful. Thank you.

The only thing that bothers me is that when these three plug-ins are turned on at the same time, the lines appear a bit dense.

Can I hide FoldLine and show FoldLineCurrent only?

Thank you for such a cool plugin ~

**Comment by gh-liu** [comment]
Update the plugin and add `vim.g.fold_line_current_fold_only = true` to your config.

Thanks, I hope the plugin helps.
