### ISSUE TITLE
feature request: add vim text-object support for current fold scope?

### ISSUE THREAD

**Issue by chaneyzorn** [gh-liu/fold_line.nvim#5]
I have tried：

1. [chrisgrieser/nvim-various-textobjs](https://github.com/chrisgrieser/nvim-various-textobjs), only closed fold can be selcted;
2. [superuser: can-vim-treat-a-folded-section-as-a-motion](https://superuser.com/a/578474), good at most time, ~~until encountered python~~, because `[z` may across different fold scopes when on the edge;
3. [mini.indentscope](https://github.com/echasnovski/mini.indentscope), indent is not exactly equivalent to fold, although still useful;

My currently config for current fold scope text-object (based on `[z`):

```
  keys = {
    {
      "az",
      ":<C-U>silent!normal![zV]z<CR>",
      mode = { "o", "x" },
      desc = "text-obj: a-fold",
    },
    {
      "iz",
      ":<C-U>silent!normal![zV]zojok<CR>",
      mode = { "o", "x" },
      desc = "text-obj: i-fold",
    },
  }
```

Or is there a way to improve it to be consistent with fold_line.nvim?

Thank you.

**Comment by gh-liu** [comment]
There is an edge case where `fold_line.nvim` only renders lines for the current window. It's impossible to get the fold if it extends outside the window.

**Comment by chaneyzorn** [comment]
whoa~, that's a good optimization.

Well, I found a sulotion from the same [superuser](https://superuser.com/questions/578432/can-vim-treat-a-folded-section-as-a-motion)

https://github.com/kana/vim-textobj-fold/blob/master/autoload/textobj/fold.vim#L66-L68

It use "``" jump back to origin level, if `[z` cause level changed.

I'll look into it some other time.

Thank you.

**Comment by gh-liu** [comment]
Thanks for the suggestion! If you write a Lua version for the fold text object, please share it here. Maybe others want something similar to what you want.

**Comment by chaneyzorn** [comment]
I want to find a more theoretical approach rather than using movement actions to simulate it.

I tried a few other ways, one of which was using [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects):

```lua
{
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  dependencies = {
    "nvim-treesitter/nvim-treesitter-textobjects",
  },
  config = function()
    require("nvim-treesitter.configs").setup({
      textobjects = {
        select = {
          enable = true,
          lookahead = true,
          keymaps = {
            ["az"] = { query = "@fold", query_group = "folds", desc = "text-obj: a-fold" },
          },
          selection_modes = {
            ["@fold"] = "V",
          },
        },
      },
    })
  end,
}
```

But it has the similar problem as `[z`.

Finally I found another solution, please see the next reply.

**Comment by chaneyzorn** [comment]
I found a more theoretical and concise way.

The solution based on [https://github.com/kevinhwang91/nvim-ufo](kevinhwang91/nvim-ufo).

Using `ufo` to get current fold scope, then set line wise selection:

```lua
-- see https://github.com/kevinhwang91/nvim-ufo/blob/1b5f2838099f283857729e820cc05e2b19df7a2c/lua/ufo/main.lua#L134
local getFoldScope = function()
  local bufnr = vim.api.nvim_get_current_buf()
  local foldRanges = require("ufo.fold").get(bufnr).foldRanges

  local lnum = vim.fn.line(".")
  local curStartLine, curEndLine = 0, 0
  for _, range in ipairs(foldRanges) do
    local sl, el = range.startLine, range.endLine
    if curStartLine < sl and sl < lnum and lnum <= el + 1 then
      curStartLine, curEndLine = sl, el
    end
  end
  return curStartLine + 1, curEndLine + 1
end

-- see https://github.com/chrisgrieser/nvim-various-textobjs/blob/c2fd8bf4c86ec8d85bd0265074711027e640863a/lua/various-textobjs/linewise-textobjs.lua#L16
local lineWiseSelect = function(startLine, endLine)
  -- save last position in jumplist like vim native textobj
  vim.cmd.normal({ "m`", bang = true })
  vim.api.nvim_win_set_cursor(0, { startLine, 0 })
  if not vim.fn.mode():find("V") then
    vim.cmd.normal({ "V", bang = true })
  end
  -- move cursor to end of visual
  vim.cmd.normal({ "o", bang = true })
  vim.api.nvim_win_set_cursor(0, { endLine, 0 })
end

-- to work with dot-repeat, replace rhs to <cmd>lua-call
vim.keymap.set({ "x", "o" }, "az", function()
  local sl, el = getFoldScope()
  -- vim.notify(("debug fold scope: %d %d"):format(sl, el))
  vim.cmd(("silent! %d,%d foldopen"):format(sl, el))
  lineWiseSelect(sl, el)
end, { silent = true, desc = "text-obj: a-fold" })

vim.keymap.set({ "x", "o" }, "iz", function()
  local tailFt = { "python" }
  local sl, el = getFoldScope()

  sl = vim.fn.min({ sl + 1, el })
  if not vim.tbl_contains(tailFt, vim.bo.ft) then
    el = vim.fn.max({ el - 1, sl })
  end

  vim.cmd(("silent! %d,%d foldopen"):format(sl, el))
  lineWiseSelect(sl, el)
end, { silent = true, desc = "text-obj: i-fold" })
```

The advantage of this solution is that all providers of `ufo` can be used, and the behavior is consistent with `ufo`.

**Comment by chaneyzorn** [comment]
Created a post on the neovim reddit: https://www.reddit.com/r/neovim/comments/1e7rteu/create_textobject_az_and_iz_for_currentfoldscope/

**Comment by gh-liu** [comment]
@chaneyzorn 

I dont know if this is a good idea, you could use the code below to get the fold scope:
```lua
local getFoldScope = function()
	local line = vim.fn.line(".")
	vim.cmd.foldclose()
	local startline = vim.fn.foldclosed(line)
	local endline = vim.fn.foldclosedend(line)
	vim.cmd.foldopen()
	return startline, endline
end


```

**Comment by chaneyzorn** [comment]
@gh-liu  Thanks, I tried it and this method also works well.  This is a good way to not rely on `ufo`.

a small improvement for no-fold-found:

```lua
local getFoldScope = function()
  local line = vim.fn.line(".")
  vim.cmd.foldclose({ mods = { silent = true, emsg_silent = true } })
  local startline = vim.fn.foldclosed(line)
  local endline = vim.fn.foldclosedend(line)
  vim.cmd.foldopen({ mods = { silent = true, emsg_silent = true } })
  if startline == -1 then
    return line, line
  end
  return startline, endline
end
```

`ufo` based method also has this problem which return line-num as 0.


PS: I learned Interesting and useful things to get `{ mods = { silent = true, emsg_silent = true } }` from `vim.api.nvim_parse_cmd`.

**Comment by chaneyzorn** [comment]
oh... I found a corner case for `foldclose`:

If the fold scope already closed, `foldclose` would close upper fold level.

`ufo` based method works well in this situation.

**Comment by chaneyzorn** [comment]
Well, improve it again (refer to [chrisgrieser/nvim-various-textobjs linewise-textobjs.lua#L41](https://github.com/chrisgrieser/nvim-various-textobjs/blob/6cc4433fd35bc44ec7699cf8456d43161b0fd83b/lua/various-textobjs/linewise-textobjs.lua#L41)):

```lua
local getFoldScope = function()
  local lnum = vim.fn.line(".")
  local startLine = vim.fn.foldclosed(lnum)
  local endLine = vim.fn.foldclosedend(lnum)
  if startLine < 0 then
    vim.cmd.foldclose({ mods = { silent = true, emsg_silent = true } })
    startLine = vim.fn.foldclosed(lnum)
    endLine = vim.fn.foldclosedend(lnum)
    vim.cmd.foldopen({ mods = { silent = true, emsg_silent = true } })
  end
  if startLine < 0 then
    return lnum, lnum
  end
  return startLine, endLine
end
```

**Comment by gh-liu** [comment]
I still think it is not the best way, but Neovim has no way to inspect folds. There is an issue [neovim#19226](https://github.com/neovim/neovim/issues/19226) discussing adding API for folds.
